module.exports = [
    { name: 'Radio Masr',                               url: 'https://live.radiomasr.net/RADIOMASR' },
    { name: 'Radio 90 90',                              url: 'https://9090streaming.mobtada.com/9090FMEGYPT' },
    { name: 'Mahatet Masr',                             url: 'https://s3.radio.co/s9cb11828c/listen' },
    { name: 'Radio Masr El-Gdida',                      url: 'https://streaming.radio.co/scc13a6b96/listen' },
    { name: 'Nogoum FM',                                url: 'https://reach-audio.esteam.rocks/radio/8000/live.mp3' },
    { name: 'Mega FM',                                  url: 'http://nebula.shoutca.st:8211/mp3' },
    { name: 'Arab Mix FM',                              url: 'https://node-17.zeno.fm/na3vpvn10qruv.acc?rj-ttl=5&rj-tok=AAABe2qd1eEAawxRDhFpcovMzg' },
    { name: 'Nile FM',                                  url: 'https://reach-audio.esteam.rocks/radio/8010/live.mp3' },
    { name: 'RadioHits',                                url: 'http://178.32.62.154:8957/;' },
    { name: 'Radio Shabab',                             url: 'https://n13.radiojar.com/a3qsqz9h2ewtv?rj-ttl=5&rj-tok=AAABe2qh60AAGn-b0bZ_9R6Z8A' },
    { name: 'El Gauna FM',                              url: 'http://82.201.132.237:8000/;stream.mp3/;' },
    { name: 'Radio Moga',                               url: 'http://eu4.fastcast4u.com:5458/;.mp3' },
    { name: 'Arab Mix',                                 url: 'https://node-27.zeno.fm/efx5psd00qruv?rj-ttl=5&rj-tok=AAABe2qc3XgAGRSML8eM76eG_Q' },
    { name: 'Radio Banha Tarab',                        url: 'http://whsh4u-panel.com:14113/stream' },
    { name: 'Radio Masrawy',                            url: 'https://9090streaming.mobtada.com/9090FMEGYPT?type=.mp3/;stream.mp3' },
    // { name: 'Coptic Orthodox',                          url: 'http://66.70.249.70:5828/stream' },
    { name: 'Radio Sotak',                              url: 'http://serv02.streamsfortheworld.com:8000/radiosotak_hi' },
    { name: 'Nota Arabia Masria',                       url: 'http://95.154.196.33:25911/live' },
    { name: 'Hawaha Betary',                            url: 'https://s44.myradiostream.com/9204/listen.mp3' },
    { name: 'Nogoum FM Mix',                            url: 'https://node-13.zeno.fm/0ms1g2tgr18uv?rj-ttl=5&rj-tok=AAABe2qtJcMAOygZe_yE1N1pGw' },
    { name: 'Radio Mundial Gospel Egito',               url: 'https://ssl.lscpainel.com.br:8254/;' },
    { name: 'Quran FM',                                 url: 'http://n0d.radiojar.com/8s5u5tpdtwzuv?listening-from-radio-garden=1629582403&rj-tok=AAABe2q3TWYAXjyxCR4rh2mtFQ&rj-ttl=5' },
    { name: 'NRG',                                      url: 'https://streamingv2.shoutcast.com/nrg-radio-ke' },
    { name: 'Nagham FM',                                url: 'https://ahmsamir.radioca.st/stream' },
    { name: 'Sha3byat',                                 url: 'http://178.32.62.154:9010/stream' },
    { name: 'On Sport FM',                              url: 'http://194.135.93.236:8010/radio.mp3' },
    { name: 'Banaha FM',                                url: 'http://live.masima.cloud:8100/stream?icy=http' },
]